### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by DavidCarl** [martindisch/oscore#4]
Hello

I am trying to build this project, however when I run the command `cargo build` it produces the following error.

```
error: failed to select a version for the requirement `aes = "^0.3.2"`
candidate versions found which didn't match: 0.7.5, 0.7.4, 0.7.3, ...
location searched: crates.io index
required by package `aes-ccm v0.4.0`
    ... which satisfies dependency `aes-ccm = "^0.4.0"` of package `oscore v0.1.0`
```

When I attempt to bump up to `aes-ccm v0.5.0` it complains about aesni and the same as before.

 ```
 error: failed to select a version for the requirement `aesni = "^0.7"`
candidate versions found which didn't match: 0.99.99, 0.10.0, 0.9.0, ...
location searched: crates.io index
required by package `aes v0.4.0`
    ... which satisfies dependency `aes = "^0.4.0"` of package `aes-ccm v0.5.0`
    ... which satisfies dependency `aes-ccm = "^0.5.0"` of package `oscore v0.1.0`
 ```
 
 Am I missing something or is there something you can help with regarding this?

**Comment by S3j5b0** [comment]
Experiencing same issue

**Comment by martindisch** [comment]
If you check this out and `cargo build` it as is, it should definitely compile. I just tested it after clearing cargo's local cache. Dependency pinning via `Cargo.lock` is here exactly to prevent this kind of situation where a build suddenly breaks. Did you by chance delete the file, update dependencies or change anything else?

Also, may I ask what your interest is regarding this project?

**Comment by DavidCarl** [comment]
Just tried to run `cargo build` on a freshly pulled image, with a cleared `~/.cargo/registry` (deleted it). However it still didnt work, I am not exactly sure what to do here. I attached a image to show the progress and what happens. And it doesnt seem that I have a Cargo.lock file, nor is here one in the github repository, as far as I noticed.

![image](https://user-images.githubusercontent.com/12971383/152300427-e2a254e9-2dcc-4570-97d2-8e2858767040.png)


> Also, may I ask what your interest is regarding this project?

Sure, its because I wanted to learn more Rust and play around with some security related topics related to my masters in computer science.

**Comment by S3j5b0** [comment]
Hi, I'll just elaborate on Davids comment :)

We are two msc student, starting on writing our thesis. For this thesis we are looking at combining EDHOC with a double ratcheting type algorithm, which we could deploy on a device. And your project is the only rust project with an implementation of it. The examples you provided also looks super helpfull, so we thought we would give your project a go.

It's strange with the build thing. I tried on two differnent linux machines with more or less clean rust installations . 
We tried deleting the `~/.cargo/regist` and running `cargo update`. The latter also complained about the same dependency.


```

$ cargo update
    Updating crates.io index
error: failed to select a version for the requirement `aes = "^0.3.2"`
candidate versions found which didn't match: 0.7.5, 0.7.4, 0.7.3, ...
location searched: crates.io index
required by package `aes-ccm v0.4.0`
    ... which satisfies dependency `aes-ccm = "^0.4.0"` of package `oscore v0.1.0 (/home/ask/Git/oscore)`
```


We tried a few things, like changing `aes-ccm = "0.4.0"` to ` aes-ccm = "0.5.0" `, since we could find that version at crates.io. 
This produced another error though.
We're really sure that we did'nt edit the cargo.lock, we're not experienced with rust enough to have a go at that. We were also wondering if it was because aes 0.3.2 has been yanked, but it says that it should still be available for download, so shouldnt it just be downloaded when we ran the build command?

Could we maybe see your cargo.lock file?

**Comment by martindisch** [comment]
Ah I get it now, my bad! Turns out I've been writing too many applications instead of libraries lately and got used to having a `Cargo.lock` checked into the repository all the time. Of course pinning dependencies only makes sense when working on a binary, library users resolve and pin dependencies themselves, which is why there's no `Cargo.lock` here.

The only reason it worked on my machine was because I still had that file lying around. You were actually right with your hunch about the yanked version. **If** you have a lock file containing one such version, Cargo will still pull it, so as to not break possibly critical builds. However, when there isn't one yet and a new one is created on the first build as in your case, it will actually refuse to pin a known yanked version. That behavior makes total sense, because you don't want to actively introduce a yanked crate into a project unless you absolutely have to. If you look for it, you'll probably find the reason why certain versions of `aes` were removed, my guess is some flaw resulting in a possible vulnerability.

Now about what to do. Since `aes` is a dependency of our dependency `aes-ccm`, one would have to update that crate. Would be easy enough, as I made it in the first place because I needed this AEAD and there wasn't a crate for that mode when I worked on this project. Since then however, the excellent Rust Crypto group has built an own [ccm](https://crates.io/crates/ccm) crate which is certainly higher quality and better maintained than mine. So I just replaced `aes-ccm` with `aes` and `ccm` directly, which was luckily pretty much a drop-in replacement as you can see in da8c062a066f5f54aa770d495b35bacd130ee8ab. It should now properly build everywhere.

You should still be aware that this is an outdated implementation of the draft as described in the readme, the other dependencies could use updates too and I'm unable to provide support for this. Other than that, have at it and good luck with your project!

**Comment by S3j5b0** [comment]
That sounds really great, impressed that it went so quick.

Were aware that the edhoc version here is old, we're probably gonna have to make a few changes to it, but I don't think there's more than 3-5 changes needed to be made (hopefully)
